checks:
    php:
        code_rating: true
        duplication: true
        version: 5.5, 5.6, 7.0 or hhvm
filter:
    excluded_paths:
        - tests/*
build:
    tests:
        override:
            -
                command: phpunit --coverage-clover=my-coverage-file
                coverage:
                    file: my-coverage-file
                    format: php-clover