
language: php

php:
  # using major version aliases

  # aliased to a recent 5.6.x version
  - 5.6
  # aliased to a recent 7.x version
  - 7.0
  # hhvm
  - hhvm

before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction

matrix:
  fast_finish: true